import type { ContentPack } from '../authoring/types';

/**
 * Content packs for the machine age. Roster names are the real designations,
 * so silhouettes, Wikipedia images and the plausibility checks all line up
 * without the author repeating themselves.
 */

export const WW1_WESTERN_FRONT: ContentPack = {
  id: 'ww1/western-front',
  name: 'Western Front 1914–18',
  period: 'ww1',
  description: 'Trench garrisons, barrages, the first tanks and scout aircraft.',
  roster: [
    { id: 'ww1_platoon', name: 'Infantry platoon', type: 'infantry', icon: 'troops', wikiTitle: 'Trench warfare' },
    { id: 'ww1_mg', name: 'Vickers machine gun', type: 'infantry', icon: 'troops', wikiTitle: 'Vickers machine gun' },
    { id: 'ww1_mortar', name: 'Trench mortar', type: 'artillery', icon: 'mortar', wikiTitle: 'Stokes mortar' },
    { id: 'ww1_18pdr', name: 'QF 18-pounder battery', type: 'artillery', icon: 'howitzer', wikiTitle: 'Ordnance QF 18-pounder' },
    { id: 'ww1_77mm', name: '7.7 cm field gun battery', type: 'artillery', icon: 'howitzer', wikiTitle: '7.7 cm FK 96 n.A.' },
    { id: 'ww1_markiv', name: 'Mark IV tank', type: 'armor', icon: 'tank', wikiTitle: 'Mark IV tank' },
    { id: 'ww1_a7v', name: 'A7V', type: 'armor', icon: 'tank', wikiTitle: 'A7V' },
    { id: 'ww1_camel', name: 'Sopwith Camel', type: 'air', icon: 'propfighter', wikiTitle: 'Sopwith Camel' },
    { id: 'ww1_drI', name: 'Fokker Dr.I', type: 'air', icon: 'propfighter', wikiTitle: 'Fokker Dr.I' },
    { id: 'ww1_lorry', name: 'Supply lorry', type: 'infantry', icon: 'truck', wikiTitle: 'Military logistics' },
    { id: 'ww1_hq', name: 'Battalion headquarters', type: 'hq', icon: 'bunker', wikiTitle: 'Dugout (shelter)' },
  ],
  macros: [
    {
      macro: 'strike-package',
      id: 'preset_creeping_barrage',
      from: 'u_18pdr',
      targets: ['First objective', 'Second objective', 'Third objective'],
      weapon: 'Creeping barrage',
      at: 20,
      intervalSeconds: 6,
      salvo: 12,
      size: 0.9,
    },
  ],
  notes: [
    'Draw the trench systems as territories and the attack as arrows across no man’s land.',
    'Aircraft observe and fight each other; they carry no guided weapons.',
  ],
};

export const WW2_COMBINED_ARMS: ContentPack = {
  id: 'ww2/combined-arms',
  name: 'Second World War combined arms',
  period: 'ww2',
  description: 'Armour, half-tracks, piston aircraft, landing craft and U-boats.',
  roster: [
    { id: 'ww2_squad', name: 'Rifle squad', type: 'infantry', icon: 'troops', wikiTitle: 'Squad' },
    { id: 'ww2_sherman', name: 'M4 Sherman', type: 'armor', icon: 'tank', wikiTitle: 'M4 Sherman' },
    { id: 'ww2_t34', name: 'T-34', type: 'armor', icon: 'tank', wikiTitle: 'T-34' },
    { id: 'ww2_panzer4', name: 'Panzer IV', type: 'armor', icon: 'tank', wikiTitle: 'Panzer IV' },
    { id: 'ww2_tiger', name: 'Tiger I', type: 'armor', icon: 'tank', wikiTitle: 'Tiger I' },
    { id: 'ww2_halftrack', name: 'M3 half-track', type: 'armor', icon: 'halftrack', wikiTitle: 'M3 half-track' },
    { id: 'ww2_jeep', name: 'Willys jeep', type: 'infantry', icon: 'jeep', wikiTitle: 'Willys MB' },
    { id: 'ww2_88', name: '8.8 cm Flak', type: 'artillery', icon: 'aagun', wikiTitle: '8.8 cm Flak 18/36/37/41' },
    { id: 'ww2_105', name: 'M2A1 105 mm battery', type: 'artillery', icon: 'howitzer', wikiTitle: 'M101 howitzer' },
    { id: 'ww2_katyusha', name: 'BM-13 Katyusha', type: 'missile', icon: 'launcher', wikiTitle: 'Katyusha rocket launcher' },
    { id: 'ww2_p51', name: 'P-51 Mustang', type: 'air', icon: 'propfighter', wikiTitle: 'North American P-51 Mustang' },
    { id: 'ww2_spitfire', name: 'Supermarine Spitfire', type: 'air', icon: 'propfighter', wikiTitle: 'Supermarine Spitfire' },
    { id: 'ww2_bf109', name: 'Messerschmitt Bf 109', type: 'air', icon: 'propfighter', wikiTitle: 'Messerschmitt Bf 109' },
    { id: 'ww2_b17', name: 'B-17 Flying Fortress', type: 'air', icon: 'propbomber', wikiTitle: 'Boeing B-17 Flying Fortress' },
    { id: 'ww2_ju87', name: 'Ju 87 Stuka', type: 'air', icon: 'propfighter', wikiTitle: 'Junkers Ju 87' },
    { id: 'ww2_c47', name: 'C-47 Skytrain', type: 'air', icon: 'proptransport', wikiTitle: 'Douglas C-47 Skytrain' },
    { id: 'ww2_lcvp', name: 'LCVP (Higgins boat)', type: 'naval', icon: 'higgins', wikiTitle: 'Higgins boat' },
    { id: 'ww2_destroyer', name: 'Destroyer', type: 'naval', icon: 'ship', wikiTitle: 'Destroyer' },
    { id: 'ww2_uboat', name: 'Type VII U-boat', type: 'naval', icon: 'uboat', wikiTitle: 'German Type VII submarine' },
  ],
  macros: [
    {
      macro: 'column',
      id: 'preset_armoured_thrust',
      factionId: 'f_axis',
      unit: { name: 'Panzer IV', type: 'armor', icon: 'tank', rosterId: 'ww2_panzer4' },
      count: 5,
      via: ['Assembly area', 'Crossroads', 'Objective'],
      spacingSeconds: 1.5,
    },
  ],
  notes: [
    'Bomb sticks and strafing runs use pattern "line" so the impacts walk along the attack axis.',
    'No jets, helicopters, drones, satellites or guided weapons.',
  ],
};

export const COLDWAR_MECH_FORCES: ContentPack = {
  id: 'coldwar/mech-forces',
  name: 'Cold War mechanised forces',
  period: 'coldwar',
  description: 'Mechanised divisions, jets, helicopters and missile air defence.',
  roster: [
    { id: 'cw_motorrifle', name: 'Motor rifle company', type: 'infantry', icon: 'troops', wikiTitle: 'Motorized infantry' },
    { id: 'cw_m60', name: 'M60 Patton', type: 'armor', icon: 'tank', wikiTitle: 'M60 tank' },
    { id: 'cw_t55', name: 'T-55', type: 'armor', icon: 'tank', wikiTitle: 'T-54/T-55' },
    { id: 'cw_t62', name: 'T-62', type: 'armor', icon: 'tank', wikiTitle: 'T-62' },
    { id: 'cw_m113', name: 'M113', type: 'armor', icon: 'apc', wikiTitle: 'M113 armored personnel carrier' },
    { id: 'cw_bmp1', name: 'BMP-1', type: 'armor', icon: 'ifv', wikiTitle: 'BMP-1' },
    { id: 'cw_m109', name: 'M109 howitzer', type: 'artillery', icon: 'spg', wikiTitle: 'M109 howitzer' },
    { id: 'cw_grad', name: 'BM-21 Grad', type: 'missile', icon: 'launcher', wikiTitle: 'BM-21 Grad' },
    { id: 'cw_zsu', name: 'ZSU-23-4 Shilka', type: 'artillery', icon: 'aagun', wikiTitle: 'ZSU-23-4 Shilka' },
    { id: 'cw_sa6', name: '2K12 Kub (SA-6)', type: 'missile', icon: 'sam', rangeKm: 24, wikiTitle: '2K12 Kub' },
    { id: 'cw_f4', name: 'F-4 Phantom II', type: 'air', icon: 'jet', wikiTitle: 'McDonnell Douglas F-4 Phantom II' },
    { id: 'cw_mig21', name: 'MiG-21', type: 'air', icon: 'jet', wikiTitle: 'Mikoyan-Gurevich MiG-21' },
    { id: 'cw_a10', name: 'A-10 Thunderbolt II', type: 'air', icon: 'jet', wikiTitle: 'Fairchild Republic A-10 Thunderbolt II' },
    { id: 'cw_huey', name: 'UH-1 Iroquois', type: 'air', icon: 'heli', wikiTitle: 'Bell UH-1 Iroquois' },
    { id: 'cw_mi24', name: 'Mi-24 Hind', type: 'air', icon: 'attackheli', wikiTitle: 'Mil Mi-24' },
    { id: 'cw_mi8', name: 'Mi-8', type: 'air', icon: 'mi8', wikiTitle: 'Mil Mi-8' },
    { id: 'cw_hq', name: 'Regimental command post', type: 'hq', icon: 'hq', wikiTitle: 'Command and control' },
  ],
  macros: [
    {
      macro: 'column',
      id: 'preset_mech_advance',
      factionId: 'f_red',
      unit: { name: 'T-62', type: 'armor', icon: 'tank', rosterId: 'cw_t62' },
      count: 6,
      via: ['Forming-up point', 'Valley road', 'Objective'],
      spacingSeconds: 2,
    },
  ],
  notes: [
    'Give air-defence units airDefenseKm and route strike aircraft around the envelope.',
    'Most fires are guns, rockets and unguided bombs; guided weapons are the exception.',
  ],
};

export const MODERN_NATO: ContentPack = {
  id: 'modern/nato',
  name: 'Modern Western forces',
  period: 'modern',
  description: 'Precision fires, rotary wing, drones and sensors.',
  roster: [
    { id: 'mod_platoon', name: 'Rifle platoon', type: 'infantry', icon: 'troops', wikiTitle: 'Platoon' },
    { id: 'mod_sof', name: 'Special operations team', type: 'infantry', icon: 'soldier', wikiTitle: 'Special forces' },
    { id: 'mod_abrams', name: 'M1A2 Abrams', type: 'armor', icon: 'abrams', wikiTitle: 'M1 Abrams' },
    { id: 'mod_bradley', name: 'M2 Bradley', type: 'armor', icon: 'bradley', wikiTitle: 'Bradley Fighting Vehicle' },
    { id: 'mod_stryker', name: 'Stryker', type: 'armor', icon: 'apc', wikiTitle: 'Stryker' },
    { id: 'mod_jltv', name: 'JLTV', type: 'infantry', icon: 'jeep', wikiTitle: 'Oshkosh JLTV' },
    { id: 'mod_m777', name: 'M777 howitzer battery', type: 'artillery', icon: 'howitzer', rangeKm: 30, wikiTitle: 'M777 howitzer' },
    { id: 'mod_himars', name: 'M142 HIMARS', type: 'missile', icon: 'launcher', rangeKm: 85, wikiTitle: 'M142 HIMARS' },
    { id: 'mod_patriot', name: 'Patriot battery', type: 'missile', icon: 'sam', rangeKm: 70, wikiTitle: 'MIM-104 Patriot' },
    { id: 'mod_f15e', name: 'F-15E Strike Eagle', type: 'air', icon: 'f15', wikiTitle: 'McDonnell Douglas F-15E Strike Eagle' },
    { id: 'mod_f22', name: 'F-22 Raptor', type: 'air', icon: 'f22', wikiTitle: 'Lockheed Martin F-22 Raptor' },
    { id: 'mod_f35', name: 'F-35A Lightning II', type: 'air', icon: 'jet', wikiTitle: 'Lockheed Martin F-35 Lightning II' },
    { id: 'mod_ah64', name: 'AH-64 Apache', type: 'air', icon: 'attackheli', wikiTitle: 'Boeing AH-64 Apache' },
    { id: 'mod_uh60', name: 'UH-60 Black Hawk', type: 'air', icon: 'heli', wikiTitle: 'Sikorsky UH-60 Black Hawk' },
    { id: 'mod_ch47', name: 'CH-47 Chinook', type: 'air', icon: 'heli', wikiTitle: 'Boeing CH-47 Chinook' },
    { id: 'mod_mq9', name: 'MQ-9 Reaper', type: 'air', icon: 'drone', wikiTitle: 'General Atomics MQ-9 Reaper' },
    { id: 'mod_ac130', name: 'AC-130J Ghostrider', type: 'air', icon: 'gunship', wikiTitle: 'Lockheed AC-130' },
    { id: 'mod_c17', name: 'C-17 Globemaster III', type: 'air', icon: 'transport', wikiTitle: 'Boeing C-17 Globemaster III' },
    { id: 'mod_imagesat', name: 'Imaging satellite', type: 'air', icon: 'satellite', wikiTitle: 'Reconnaissance satellite' },
    { id: 'mod_hq', name: 'Tactical operations centre', type: 'hq', icon: 'hq', wikiTitle: 'Command and control' },
  ],
  macros: [
    {
      macro: 'strike-package',
      id: 'preset_precision_strike',
      from: 'u_f15e',
      targets: ['u_t72_lead', 'u_t72_second'],
      weapon: 'GBU-38 JDAM',
      at: 'k_strike',
      intervalSeconds: 2.5,
    },
  ],
  notes: [
    'Give precision weapons an explicit launchAt inside the shooter’s route, and a targetUnitId when the target moves.',
    'Show the sensing as well as the shooting: sensorKm, airDefenseKm, datalink effects, a satellite pass.',
  ],
};

export const MODERN_OPFOR: ContentPack = {
  id: 'modern/opfor',
  name: 'Modern Eastern and irregular forces',
  period: 'modern',
  description: 'Mechanised regiments, technicals, layered air defence.',
  roster: [
    { id: 'opf_motorrifle', name: 'Motor rifle company', type: 'infantry', icon: 'troops', wikiTitle: 'Motorized infantry' },
    { id: 'opf_fighters', name: 'Irregular fighters', type: 'infantry', icon: 'troops', wikiTitle: 'Irregular military' },
    { id: 'opf_t72', name: 'T-72B3', type: 'armor', icon: 'tank', wikiTitle: 'T-72' },
    { id: 'opf_t90', name: 'T-90', type: 'armor', icon: 'tank', wikiTitle: 'T-90' },
    { id: 'opf_bmp2', name: 'BMP-2', type: 'armor', icon: 'ifv', wikiTitle: 'BMP-2' },
    { id: 'opf_btr82', name: 'BTR-82A', type: 'armor', icon: 'apc', wikiTitle: 'BTR-82' },
    { id: 'opf_technical', name: 'Technical', type: 'armor', icon: 'truck', wikiTitle: 'Technical (vehicle)' },
    { id: 'opf_d30', name: 'D-30 howitzer battery', type: 'artillery', icon: 'howitzer', rangeKm: 15, wikiTitle: 'D-30 howitzer' },
    { id: 'opf_msta', name: '2S19 Msta-S', type: 'artillery', icon: 'spg', rangeKm: 24, wikiTitle: '2S19 Msta' },
    { id: 'opf_grad', name: 'BM-21 Grad', type: 'missile', icon: 'launcher', rangeKm: 21, wikiTitle: 'BM-21 Grad' },
    { id: 'opf_s400', name: 'S-400 battery', type: 'missile', icon: 'sam', rangeKm: 250, wikiTitle: 'S-400 missile system' },
    { id: 'opf_pantsir', name: 'Pantsir-S1', type: 'missile', icon: 'sam', rangeKm: 20, wikiTitle: 'Pantsir missile system' },
    { id: 'opf_su25', name: 'Su-25', type: 'air', icon: 'jet', wikiTitle: 'Sukhoi Su-25' },
    { id: 'opf_su34', name: 'Su-34', type: 'air', icon: 'jet', wikiTitle: 'Sukhoi Su-34' },
    { id: 'opf_mi8', name: 'Mi-8', type: 'air', icon: 'mi8', wikiTitle: 'Mil Mi-8' },
    { id: 'opf_mi24', name: 'Mi-24', type: 'air', icon: 'attackheli', wikiTitle: 'Mil Mi-24' },
    { id: 'opf_shahed', name: 'One-way attack drone', type: 'air', icon: 'drone', wikiTitle: 'Loitering munition' },
    { id: 'opf_radar', name: 'Counter-battery radar', type: 'hq', icon: 'radar', wikiTitle: 'Counter-battery radar' },
  ],
  macros: [
    {
      macro: 'column',
      id: 'preset_attack_column',
      factionId: 'f_red',
      unit: { name: 'T-72B3', type: 'armor', icon: 'tank', rosterId: 'opf_t72' },
      count: 6,
      via: ['Staging area', 'River road', 'Objective'],
      spacingSeconds: 2,
    },
  ],
  notes: [
    'Layer the air defence: a long-range battery plus a short-range point defence reads clearly on the map.',
    'Counter-battery fire is a good use of a datalink effect between a radar and a gun line.',
  ],
};
