import type { StyleSpecification } from 'maplibre-gl';

/**
 * Classic battle-map theme: tan land, blue water.
 * Built on OpenMapTiles vector schema served by OpenFreeMap (OSM data).
 */
export const TAN_BLUE_STYLE: StyleSpecification = {
  version: 8,
  name: 'Conflict Sandbox Tan',
  glyphs:
    'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  sources: {
    openmaptiles: {
      type: 'vector',
      url: 'https://tiles.openfreemap.org/planet',
    },
    'terrain-dem': {
      type: 'raster-dem',
      tiles: [
        'https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png',
      ],
      encoding: 'terrarium',
      tileSize: 256,
      maxzoom: 15,
    },
  },
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: { 'background-color': '#e9dec6' },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      paint: {
        'fill-color': '#a3b7ba',
        'fill-opacity': 1,
      },
    },
    {
      id: 'landcover-ice',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', ['get', 'class'], 'ice'],
      paint: { 'fill-color': '#f0ede6' },
    },
    {
      id: 'landcover-sand',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', ['get', 'class'], 'sand'],
      paint: { 'fill-color': '#ece2c9' },
    },
    {
      id: 'landcover-wood',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: [
        'in',
        ['get', 'class'],
        ['literal', ['wood', 'forest', 'grass']],
      ],
      paint: {
        'fill-color': '#d3c98f',
        'fill-opacity': 0.45,
      },
    },
    {
      id: 'hillshade',
      type: 'hillshade',
      source: 'terrain-dem',
      paint: {
        'hillshade-exaggeration': 0.14,
        'hillshade-shadow-color': '#6b5d42',
        'hillshade-highlight-color': '#fbf4e2',
        'hillshade-accent-color': '#6a5b3e',
        'hillshade-illumination-direction': 315,
      },
    },
    {
      id: 'park',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'park',
      paint: { 'fill-color': '#d3c98f', 'fill-opacity': 0.35 },
    },
    {
      id: 'waterway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      paint: {
        'line-color': '#93aeb3',
        'line-width': ['interpolate', ['linear'], ['zoom'], 4, 0.6, 12, 2.4],
      },
    },
    {
      id: 'water-edge',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'water',
      minzoom: 5,
      paint: { 'line-color': '#7f989d', 'line-width': 0.7, 'line-opacity': 0.6 },
    },
    {
      id: 'roads-casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 7,
      filter: ['in', ['get', 'class'], ['literal', ['motorway', 'trunk', 'primary', 'secondary']]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#b9aa8a',
        'line-width': ['interpolate', ['linear'], ['zoom'], 7, 1, 12, 3, 15, 5],
        'line-opacity': 0.45,
      },
    },
    {
      id: 'roads',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 7,
      filter: ['in', ['get', 'class'], ['literal', ['motorway', 'trunk', 'primary', 'secondary']]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#f6efdf',
        'line-width': ['interpolate', ['linear'], ['zoom'], 7, 0.5, 12, 1.8, 15, 3.5],
      },
    },
    {
      id: 'tracks',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      minzoom: 11,
      filter: ['in', ['get', 'class'], ['literal', ['tertiary', 'minor', 'track']]],
      paint: {
        'line-color': '#8b7a58',
        'line-width': 0.8,
        'line-opacity': 0.5,
        'line-dasharray': [3, 2],
      },
    },
    {
      id: 'boundary-country',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['<=', ['get', 'admin_level'], 2],
      paint: {
        'line-color': '#8a7a5a',
        'line-width': ['interpolate', ['linear'], ['zoom'], 2, 0.8, 8, 1.8],
        'line-dasharray': [3, 2],
        'line-opacity': 0.8,
      },
    },
    {
      id: 'boundary-state',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: [
        'all',
        ['>', ['get', 'admin_level'], 2],
        ['<=', ['get', 'admin_level'], 4],
      ],
      minzoom: 3,
      paint: {
        'line-color': '#a08e6a',
        'line-width': 0.7,
        'line-dasharray': [2, 2],
        'line-opacity': 0.55,
      },
    },
    {
      id: 'buildings-3d',
      type: 'fill-extrusion',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 12,
      paint: {
        'fill-extrusion-color': '#d6c9ad',
        'fill-extrusion-height': [
          'interpolate',
          ['linear'],
          ['zoom'],
          12,
          0,
          13,
          ['coalesce', ['get', 'render_height'], 12],
        ],
        'fill-extrusion-base': ['coalesce', ['get', 'render_min_height'], 0],
        'fill-extrusion-opacity': 0.85,
      },
    },
    {
      id: 'place-country',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'country'],
      minzoom: 1,
      layout: {
        'text-field': ['get', 'name:en'],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 2, 9, 6, 13],
        'text-transform': 'uppercase',
        'text-letter-spacing': 0.12,
      },
      paint: {
        'text-color': '#4a3f2a',
        'text-halo-color': '#e9dec6',
        'text-halo-width': 1.6,
      },
    },
    {
      id: 'place-state',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'state'],
      minzoom: 3,
      layout: {
        'text-field': ['get', 'name:en'],
        'text-font': ['Noto Sans Regular'],
        'text-size': 10,
        'text-transform': 'uppercase',
        'text-letter-spacing': 0.1,
      },
      paint: {
        'text-color': '#6a5c40',
        'text-halo-color': '#e9dec6',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place-city',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: [
        'in',
        ['get', 'class'],
        ['literal', ['city', 'town']],
      ],
      minzoom: 4,
      layout: {
        'text-field': ['get', 'name:en'],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 4, 10, 10, 14],
        'icon-image': 'city-square',
        'icon-size': ['interpolate', ['linear'], ['zoom'], 4, 0.55, 10, 0.8],
        'text-anchor': 'left',
        'text-offset': [0.9, 0],
        'icon-allow-overlap': false,
        'text-optional': true,
      },
      paint: {
        'text-color': '#3d3423',
        'text-halo-color': '#e9dec6',
        'text-halo-width': 1.2,
      },
    },
    {
      id: 'place-capital',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'capital'], 2],
      minzoom: 3,
      layout: {
        'text-field': ['get', 'name:en'],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3, 10, 8, 14],
      },
      paint: {
        'text-color': '#2e2617',
        'text-halo-color': '#e9dec6',
        'text-halo-width': 1.6,
      },
    },
  ],
};
